[build]
    command = "npm install && npm run build"
    functions = "functions"
## Redirect for router.get('/secret/:id'
[[redirects]]
    from = "/secret/*"
    to = "/.netlify/functions/app/secret/:splat"