[build]
 command = "cd client && npm install && npm run build"
 functions = "functions"
  publish = "client/dist"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [[redirects]]
  from = "/.well-known/apple-developer-merchantid-domain-association"
  to = "/.netlify/functions/domain-verification"
  status = 200
