name: Slack Notification on New Issue

on:
  issues:
    types: [opened]

jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_CHANNEL: "#solution-engineering"
            SLACK_COLOR: "#FFFF00"
            SLACK_ICON: https://avatars.githubusercontent.com/u/64789791?s=200&v=4
            SLACK_MESSAGE: "Link to issue: [${{ github.event.issue.title }}](https://github.com/${{ github.repository }}/issues)"
            SLACK_TITLE: New issue created in ${{ github.repository }}
            SLACK_USERNAME: GH Issue Notice
            SLACKIFY_MARKDOWN: true
