name: Slack Notification on New Issue

on:
  issues:
    types: [opened]

jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: "#solution-engineering"
          text: "New issue created: ${{ github.event.issue.title }}"
